//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Solution2.Module.BusinessObjects.Database
{

    public partial class OrderItems : XPLiteObject
    {
        int fId;
        [Key]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        Order fOrderId;
        [Association(@"OrderItemsReferencesOrder")]
        public Order OrderId
        {
            get { return fOrderId; }
            set { SetPropertyValue<Order>(nameof(OrderId), ref fOrderId, value); }
        }
        ProductItem fProductItemId;
        [Association(@"OrderItemsReferencesProductItem")]
        public ProductItem ProductItemId
        {
            get { return fProductItemId; }
            set { SetPropertyValue<ProductItem>(nameof(ProductItemId), ref fProductItemId, value); }
        }
    }

}
