//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Solution2.Module.BusinessObjects.Database
{

    public partial class OrderStatusType : XPLiteObject
    {
        int fId;
        [Key]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fStatusType;
        [Indexed(Name = @"UQ__OrderSta__AA2EC4A38EC50211", Unique = true)]
        [Size(20)]
        public string StatusType
        {
            get { return fStatusType; }
            set { SetPropertyValue<string>(nameof(StatusType), ref fStatusType, value); }
        }
        [Association(@"OrderReferencesOrderStatusType")]
        public XPCollection<Order> Orders { get { return GetCollection<Order>(nameof(Orders)); } }
    }

}
