//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Solution2.Module.BusinessObjects.Database
{

    public partial class ProductItem : XPLiteObject
    {
        int fId;
        [Key]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fItemName;
        [Size(50)]
        public string ItemName
        {
            get { return fItemName; }
            set { SetPropertyValue<string>(nameof(ItemName), ref fItemName, value); }
        }
        double fItemPrice;
        public double ItemPrice
        {
            get { return fItemPrice; }
            set { SetPropertyValue<double>(nameof(ItemPrice), ref fItemPrice, value); }
        }
        [Association(@"OrderItemsReferencesProductItem")]
        public XPCollection<OrderItems> OrderItemsCollection { get { return GetCollection<OrderItems>(nameof(OrderItemsCollection)); } }
    }

}
