//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Solution2.Module.BusinessObjects.Database
{

    public partial class Order : XPLiteObject
    {
        int fId;
        [Key]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        Customer fCustomerId;
        [Association(@"OrderReferencesCustomer")]
        public Customer CustomerId
        {
            get { return fCustomerId; }
            set { SetPropertyValue<Customer>(nameof(CustomerId), ref fCustomerId, value); }
        }
        DateTime fOrderDate;
        public DateTime OrderDate
        {
            get { return fOrderDate; }
            set { SetPropertyValue<DateTime>(nameof(OrderDate), ref fOrderDate, value); }
        }
        string fOrderNum;
        [Size(50)]
        public string OrderNum
        {
            get { return fOrderNum; }
            set { SetPropertyValue<string>(nameof(OrderNum), ref fOrderNum, value); }
        }
        OrderStatusType fOrderStatus;
        [Association(@"OrderReferencesOrderStatusType")]
        public OrderStatusType OrderStatus
        {
            get { return fOrderStatus; }
            set { SetPropertyValue<OrderStatusType>(nameof(OrderStatus), ref fOrderStatus, value); }
        }
        [Association(@"OrderItemsReferencesOrder")]
        public XPCollection<OrderItems> OrderItemsCollection { get { return GetCollection<OrderItems>(nameof(OrderItemsCollection)); } }
    }

}
