//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace InventoryXPO
{

    public partial class Item : XPObject
    {
        string fItemName;
        /// <summary>
        /// Product Name
        /// </summary>
        [Size(200)]
        [DevExpress.Xpo.DisplayName(@"Item Name")]
        public string ItemName
        {
            get { return fItemName; }
            set { SetPropertyValue<string>(nameof(ItemName), ref fItemName, value); }
        }
        decimal fItemPriceInStock;
        /// <summary>
        /// Item Price in Stock
        /// </summary>
        public decimal ItemPriceInStock
        {
            get { return fItemPriceInStock; }
            set { SetPropertyValue<decimal>(nameof(ItemPriceInStock), ref fItemPriceInStock, value); }
        }
        OrderDetail fOrderDetail;
        [Association(@"ItemReferencesOrderDetail")]
        public OrderDetail OrderDetail
        {
            get { return fOrderDetail; }
            set { SetPropertyValue<OrderDetail>(nameof(OrderDetail), ref fOrderDetail, value); }
        }
        [Association(@"ItemInStockReferencesItem")]
        public XPCollection<ItemInStock> ItemInStocks { get { return GetCollection<ItemInStock>(nameof(ItemInStocks)); } }
    }

}
