//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace InventoryXPO
{

    public partial class ItemInStock : XPObject
    {
        long fQuantityOnStock;
        public long QuantityOnStock
        {
            get { return fQuantityOnStock; }
            set { SetPropertyValue<long>(nameof(QuantityOnStock), ref fQuantityOnStock, value); }
        }
        Item fItemId;
        [Association(@"ItemInStockReferencesItem")]
        public Item ItemId
        {
            get { return fItemId; }
            set { SetPropertyValue<Item>(nameof(ItemId), ref fItemId, value); }
        }
    }

}
