//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace InventoryXPO
{

    public partial class OrderDetail : XPObject
    {
        Order fOrderId;
        [Association(@"OrderDetailReferencesOrder")]
        [DevExpress.Xpo.DisplayName(@"Order Id")]
        public Order OrderId
        {
            get { return fOrderId; }
            set { SetPropertyValue<Order>(nameof(OrderId), ref fOrderId, value); }
        }
        Item fItemId;
        public Item ItemId
        {
            get { return fItemId; }
            set { SetPropertyValue<Item>(nameof(ItemId), ref fItemId, value); }
        }
        short fOrderDetailQuantity;
        [DevExpress.Xpo.DisplayName(@"Order Quantity")]
        public short OrderDetailQuantity
        {
            get { return fOrderDetailQuantity; }
            set { SetPropertyValue<short>(nameof(OrderDetailQuantity), ref fOrderDetailQuantity, value); }
        }
        [Association(@"OrderDetailReferencesItem")]
        public XPCollection<Item> Items { get { return GetCollection<Item>(nameof(Items)); } }
    }

}
