//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace InventoryXPO
{

    public partial class OrderStatusEnumTable : XPObject
    {
        string fOrderStatusAsText;
        [Indexed(Name = @"IndexOrderStatusAsText", Unique = true)]
        public string OrderStatusAsText
        {
            get { return fOrderStatusAsText; }
            set { SetPropertyValue<string>(nameof(OrderStatusAsText), ref fOrderStatusAsText, value); }
        }
        short fValue;
        [Indexed(Name = @"IndexValue", Unique = true)]
        public short Value
        {
            get { return fValue; }
            set { SetPropertyValue<short>(nameof(Value), ref fValue, value); }
        }
    }

}
