//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace InventoryXPO
{

    public partial class Order : XPObject
    {
        DateTime fOrderDate;
        [DevExpress.Xpo.DisplayName(@"Order Date")]
        public DateTime OrderDate
        {
            get { return fOrderDate; }
            set { SetPropertyValue<DateTime>(nameof(OrderDate), ref fOrderDate, value); }
        }
        Customer fCustomer;
        [Association(@"CustomerOrders")]
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>(nameof(Customer), ref fCustomer, value); }
        }
        string fOrderNum;
        [Size(40)]
        [DevExpress.Xpo.DisplayName(@"Order Number")]
        public string OrderNum
        {
            get { return fOrderNum; }
            set { SetPropertyValue<string>(nameof(OrderNum), ref fOrderNum, value); }
        }
        string fOrderStatus;
        [Persistent(@"OrderStatusType")]
        [ValueConverter(typeof(InventoryXPO.Tools.OrderStatusTypeValueConverter))]
        [DevExpress.Xpo.DisplayName(@"Order Status")]
        public string OrderStatus
        {
            get { return fOrderStatus; }
            set { SetPropertyValue<string>(nameof(OrderStatus), ref fOrderStatus, value); }
        }
    }

}
