//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace InventoryXPO
{

    public partial class OrderDetail : XPObject
    {
        Order fOrder;
        [DevExpress.Xpo.DisplayName(@"Order Id")]
        public Order Order
        {
            get { return fOrder; }
            set { SetPropertyValue<Order>(nameof(Order), ref fOrder, value); }
        }
        short fOrderDetailQuantity;
        [DevExpress.Xpo.DisplayName(@"Order Quantity")]
        public short OrderDetailQuantity
        {
            get { return fOrderDetailQuantity; }
            set { SetPropertyValue<short>(nameof(OrderDetailQuantity), ref fOrderDetailQuantity, value); }
        }
        decimal fOrderDetailPrice;
        /// <summary>
        /// Item Price in Order
        /// </summary>
        public decimal OrderDetailPrice
        {
            get { return fOrderDetailPrice; }
            set { SetPropertyValue<decimal>(nameof(OrderDetailPrice), ref fOrderDetailPrice, value); }
        }
        [Association(@"ItemReferencesOrderDetail")]
        public XPCollection<Item> Items { get { return GetCollection<Item>(nameof(Items)); } }
    }

}
